require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SimpleQuestionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # SimpleQuestion. As you add validations to SimpleQuestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SimpleQuestionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all simple_questions as @simple_questions" do
      simple_question = SimpleQuestion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:simple_questions)).to eq([simple_question])
    end
  end

  describe "GET show" do
    it "assigns the requested simple_question as @simple_question" do
      simple_question = SimpleQuestion.create! valid_attributes
      get :show, {:id => simple_question.to_param}, valid_session
      expect(assigns(:simple_question)).to eq(simple_question)
    end
  end

  describe "GET new" do
    it "assigns a new simple_question as @simple_question" do
      get :new, {}, valid_session
      expect(assigns(:simple_question)).to be_a_new(SimpleQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested simple_question as @simple_question" do
      simple_question = SimpleQuestion.create! valid_attributes
      get :edit, {:id => simple_question.to_param}, valid_session
      expect(assigns(:simple_question)).to eq(simple_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SimpleQuestion" do
        expect {
          post :create, {:simple_question => valid_attributes}, valid_session
        }.to change(SimpleQuestion, :count).by(1)
      end

      it "assigns a newly created simple_question as @simple_question" do
        post :create, {:simple_question => valid_attributes}, valid_session
        expect(assigns(:simple_question)).to be_a(SimpleQuestion)
        expect(assigns(:simple_question)).to be_persisted
      end

      it "redirects to the created simple_question" do
        post :create, {:simple_question => valid_attributes}, valid_session
        expect(response).to redirect_to(SimpleQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved simple_question as @simple_question" do
        post :create, {:simple_question => invalid_attributes}, valid_session
        expect(assigns(:simple_question)).to be_a_new(SimpleQuestion)
      end

      it "re-renders the 'new' template" do
        post :create, {:simple_question => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested simple_question" do
        simple_question = SimpleQuestion.create! valid_attributes
        put :update, {:id => simple_question.to_param, :simple_question => new_attributes}, valid_session
        simple_question.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested simple_question as @simple_question" do
        simple_question = SimpleQuestion.create! valid_attributes
        put :update, {:id => simple_question.to_param, :simple_question => valid_attributes}, valid_session
        expect(assigns(:simple_question)).to eq(simple_question)
      end

      it "redirects to the simple_question" do
        simple_question = SimpleQuestion.create! valid_attributes
        put :update, {:id => simple_question.to_param, :simple_question => valid_attributes}, valid_session
        expect(response).to redirect_to(simple_question)
      end
    end

    describe "with invalid params" do
      it "assigns the simple_question as @simple_question" do
        simple_question = SimpleQuestion.create! valid_attributes
        put :update, {:id => simple_question.to_param, :simple_question => invalid_attributes}, valid_session
        expect(assigns(:simple_question)).to eq(simple_question)
      end

      it "re-renders the 'edit' template" do
        simple_question = SimpleQuestion.create! valid_attributes
        put :update, {:id => simple_question.to_param, :simple_question => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested simple_question" do
      simple_question = SimpleQuestion.create! valid_attributes
      expect {
        delete :destroy, {:id => simple_question.to_param}, valid_session
      }.to change(SimpleQuestion, :count).by(-1)
    end

    it "redirects to the simple_questions list" do
      simple_question = SimpleQuestion.create! valid_attributes
      delete :destroy, {:id => simple_question.to_param}, valid_session
      expect(response).to redirect_to(simple_questions_url)
    end
  end

end
